---
# Instance: argo-events
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argo-events
  namespace: flux-system
spec:
  targetNamespace: argo-events
  chart:
    spec:
      chart: argo-events
      interval: 60m
      sourceRef:
        kind: HelmRepository
        name: argo
      version: 2.4.*
  interval: 60m
  install:
    createNamespace: true
    crds: Create
    disableWait: false
    disableWaitForJobs: false
    remediation:
      retries: -1
  releaseName: argo-events
  test:
    enable: false
  timeout: 5m
  upgrade:
    crds: CreateReplace
    disableWait: false
    disableWaitForJobs: false
    remediation:
      retries: -1
  values:
    installCRDs: true

