---
# Instance: kafka-cd
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka
  namespace: flux-system
spec:
  targetNamespace: kafka
  chart:
    spec:
      chart: kafka
      interval: 60m
      sourceRef:
        kind: HelmRepository
        name: kafka
      version: 31.1.*
  interval: 60m
  install:
    createNamespace: true
    crds: Create
    disableWait: false
    disableWaitForJobs: false
    remediation:
      retries: -1
  releaseName: kafka
  test:
    enable: false
  timeout: 5m
  upgrade:
    crds: CreateReplace
    disableWait: false
    disableWaitForJobs: false
    remediation:
      retries: -1
  values:
    installCRDs: true
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kafka
  namespace: flux-system
spec:
  interval: 12h
  provider: generic
  url: https://charts.bitnami.com/bitnami
