apiVersion: v1
kind: Service
metadata:
  name: cli-playground
spec:
  selector:
    app: cli-playground
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli-playground
  labels:
    app: cli-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cli-playground
  template:
    metadata:
      name: cli-playground
      labels:
        app: cli-playground
    spec:
      containers:
        - name: cli-playground
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
