---
# Instance: argo-cd
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: flux-system
spec:
  targetNamespace: vault
  chart:
    spec:
      chart: vault
      interval: 60m
      sourceRef:
        kind: HelmRepository
        name: vault
      version: 0.29.*
  interval: 60m
  install:
    createNamespace: true
    crds: Create
    disableWait: false
    disableWaitForJobs: false
    remediation:
      retries: -1
  releaseName: argo-cd
  test:
    enable: false
  timeout: 5m
  upgrade:
    crds: CreateReplace
    disableWait: false
    disableWaitForJobs: false
    remediation:
      retries: -1
  values:
    installCRDs: true
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 12h
  provider: generic
  url: https://helm.releases.hashicorp.com
