apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: silly-demo
spec:
  dependsOn:
#  - provider: xpkg.upbound.io/upbound/provider-gcp-storage
#    version: v1
#  - provider: xpkg.upbound.io/upbound/provider-aws-s3
#    version: v1
  - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
    version: v0.4.1
  - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
    version: v0.8.1
