
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: crossplane-system # namespace must be the same as the namespace of the secret
spec:
  provider:
    gcpsm: # gcpsm provider
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: es-secret
            key: creds
      projectID: playground-447016
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: configs
  namespace: crossplane-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: config-secrets  # name of the k8s Secret to be created
    # Enum with values: 'Owner', 'Merge', or 'None'
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: manager-secrets
        version: latest
---

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: apps # namespace must be the same as the namespace of the secret
spec:
  provider:
    gcpsm: # gcpsm provider
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: es-secret
            key: creds
      projectID: playground-447016
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: configs
  namespace: apps
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: config-secrets  # name of the k8s Secret to be created
    # Enum with values: 'Owner', 'Merge', or 'None'
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: app-secrets
        version: latest

