---
# Instance: traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    app.kubernetes.io/managed-by: timoni
    app.kubernetes.io/name: traefik
    app.kubernetes.io/version: 2.4.0-2
  name: traefik
  namespace: flux-system
spec:
  targetNamespace: traefik
  chart:
    metadata:
      labels:
        app.kubernetes.io/managed-by: timoni
        app.kubernetes.io/name: traefik
        app.kubernetes.io/version: 2.4.0-2
    spec:
      chart: traefik
      interval: 60m
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: 33.2.*
  install:
    createNamespace: true
    crds: Create
    disableWait: false
    disableWaitForJobs: false
    remediation:
      retries: -1
  interval: 60m
  releaseName: traefik
  test:
    enable: false
  timeout: 5m
  upgrade:
    crds: CreateReplace
    disableWait: false
    disableWaitForJobs: false
    remediation:
      retries: -1
  values: { }
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  labels:
    app.kubernetes.io/managed-by: timoni
    app.kubernetes.io/name: traefik
    app.kubernetes.io/version: 2.4.0-2
  name: traefik
  namespace: flux-system
spec:
  interval: 12h
  provider: generic
  url: https://traefik.github.io/charts
