apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd # ArgoCD control namespace
spec:
  destination:
    namespace: external-secrets # Target namespace where resources will be deployed
    server: https://kubernetes.default.svc # Cluster to deploy to (default cluster)
  source:
    repoURL: https://charts.external-secrets.io # Replace with the actual Helm repository URL
    chart: external-secrets
    targetRevision: 0.9.* # Version of the chart to deploy
    helm:
      releaseName: external-secrets
      parameters:
        - name: installCRDs
          value: "true"
  project: default # ArgoCD project (use `default` unless you have a specific project setup)
  syncPolicy:
    automated: # Optional: Enables automated synchronization
      prune: true # Allow resources to be pruned if they are removed from the chart
      selfHeal: true # Automatically sync if drift is detected
    syncOptions:
      - CreateNamespace=true # Automatically create the namespace if it doesn't exist
