---
# Instance: external-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    app.kubernetes.io/managed-by: timoni
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/version: 2.4.0-2
  name: external-secrets
  namespace: flux-system
spec:
  targetNamespace: external-secrets
  chart:
    metadata:
      labels:
        app.kubernetes.io/managed-by: timoni
        app.kubernetes.io/name: external-secrets
        app.kubernetes.io/version: 2.4.0-2
    spec:
      chart: external-secrets
      interval: 60m
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      version: 0.9.*
  install:
    createNamespace: true
    crds: Create
    disableWait: false
    disableWaitForJobs: false
    remediation:
      retries: -1
  interval: 60m
  releaseName: external-secrets
  test:
    enable: false
  timeout: 5m
  upgrade:
    crds: CreateReplace
    disableWait: false
    disableWaitForJobs: false
    remediation:
      retries: -1
  values:
    installCRDs: true
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  labels:
    app.kubernetes.io/managed-by: timoni
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/version: 2.4.0-2
  name: external-secrets
  namespace: flux-system
spec:
  interval: 12h
  provider: generic
  url: https://charts.external-secrets.io
