---
# Instance: keda
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
#  labels:
#    app.kubernetes.io/managed-by: timoni
#    app.kubernetes.io/name: keda
#    app.kubernetes.io/version: 2.4.0-2
  name: keda
  namespace: flux-system
spec:
  targetNamespace: keda
  chart:
#    metadata:
#      labels:
#        app.kubernetes.io/managed-by: timoni
#        app.kubernetes.io/name: keda
#        app.kubernetes.io/version: 2.4.0-2
    spec:
      chart: keda
      interval: 60m
      sourceRef:
        kind: HelmRepository
        name: keda
      version: 2.14.*
  install:
    createNamespace: true
    crds: Create
    disableWait: false
    disableWaitForJobs: false
    remediation:
      retries: -1
  interval: 60m
  releaseName: keda
  test:
    enable: false
  timeout: 5m
  upgrade:
    crds: CreateReplace
    disableWait: false
    disableWaitForJobs: false
    remediation:
      retries: -1
  values: { }
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
#  labels:
#    app.kubernetes.io/managed-by: timoni
#    app.kubernetes.io/name: keda
#    app.kubernetes.io/version: 2.4.0-2
  name: keda
  namespace: flux-system
spec:
  interval: 12h
  provider: generic
  url: https://kedacore.github.io/charts
