[package]
name = "lili_registry"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = {version = "1.43.0", features = ["full", "time"]}
rand = "0.9.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
