apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd # ArgoCD control namespace
spec:
  destination:
    namespace: argo-rollouts # Target namespace where resources will be deployed
    server: https://kubernetes.default.svc # Cluster to deploy to (default cluster)
  source:
    repoURL: https://argoproj.github.io/argo-helm # Replace with the actual Helm repository URL
    chart: argo-rollouts
    targetRevision: 2.38.* # Version of the chart to deploy
    helm:
      releaseName: argo-rollouts
      parameters:
        - name: installCRDs
          value: "true"
  project: default # ArgoCD project (use `default` unless you have a specific project setup)
  syncPolicy:
    automated: # Optional: Enables automated synchronization
      prune: true # Allow resources to be pruned if they are removed from the chart
      selfHeal: true # Automatically sync if drift is detected
    syncOptions:
      - CreateNamespace=true # Automatically create the namespace if it doesn't exist
