---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-crd-cleaner
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-crd-cleaner-role
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["delete", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-crd-cleaner-binding
subjects:
  - kind: ServiceAccount
    name: prometheus-crd-cleaner
    namespace: default
roleRef:
  kind: ClusterRole
  name: prometheus-crd-cleaner-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-prometheus-crds
  annotations:
    argocd.argoproj.io/hook: PreDelete
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: prometheus-crd-cleaner
      containers:
        - name: delete-crds
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              kubectl delete crds \
              podmonitors.monitoring.coreos.com \
              probes.monitoring.coreos.com \
              alertmanagerconfigs.monitoring.coreos.com \
              prometheusrules.monitoring.coreos.com \
              scrapeconfigs.monitoring.coreos.com \
              servicemonitors.monitoring.coreos.com
