---
# Instance: prometheus
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    app.kubernetes.io/managed-by: timoni
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/version: 2.4.0-2
  # The HelmRelease is defined in this namespace,
  # but you can also choose a different namespace for your HelmRelease CR itself
  # and still target the "prometheus" namespace for the actual release.
  name: prometheus
  namespace: flux-system
spec:
  # This is the namespace where the chart will be installed.
  targetNamespace: prometheus

  chart:
    metadata:
      labels:
        app.kubernetes.io/managed-by: timoni
        app.kubernetes.io/name: prometheus
        app.kubernetes.io/version: 2.4.0-2
    spec:
      chart: kube-prometheus-stack
      interval: 60m
      sourceRef:
        kind: HelmRepository
        name: prometheus
      version: 60.1.*

  # Instruct Flux to create the namespace if it doesn't exist
  install:
    createNamespace: true
    crds: Create
    disableWait: false
    disableWaitForJobs: false
    remediation:
      retries: -1

  interval: 60m
  releaseName: prometheus
  test:
    enable: false
  timeout: 5m

  upgrade:
    #    createNamespace: true          # (optional to also ensure namespace creation on upgrade)
    crds: CreateReplace
    disableWait: false
    disableWaitForJobs: false
    remediation:
      retries: -1

  values:
    installCRDs: true

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  labels:
    app.kubernetes.io/managed-by: timoni
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/version: 2.4.0-2
  name: prometheus
  namespace: flux-system
spec:
  interval: 12h
  provider: generic
  url: https://prometheus-community.github.io/helm-charts
