apiVersion: redis.gcp.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: redis/v1beta1/cluster
  labels:
    testing.upbound.io/example-name: cluster-ha
  name: cluster-ha
spec:
  forProvider:
    authorizationMode: AUTH_MODE_DISABLED
    nodeType: REDIS_SHARED_CORE_NANO
    pscConfigs:
      - networkSelector:
          matchLabels:
            testing.upbound.io/example-name: producer_net
    redisConfigs:
      maxmemory-policy: volatile-ttl
    region: us-central1
    replicaCount: 1
    shardCount: 3
    transitEncryptionMode: TRANSIT_ENCRYPTION_MODE_DISABLED
    zoneDistributionConfig:
      mode: MULTI_ZONE
