---
# Instance: crossplane
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    app.kubernetes.io/managed-by: timoni
    app.kubernetes.io/name: crossplane
    app.kubernetes.io/version: 2.4.0-2
  name: crossplane
  namespace: flux-system
spec:
  targetNamespace: crossplane
  chart:
    metadata:
      labels:
        app.kubernetes.io/managed-by: timoni
        app.kubernetes.io/name: crossplane
        app.kubernetes.io/version: 2.4.0-2
    spec:
      chart: crossplane
      interval: 60m
      sourceRef:
        kind: HelmRepository
        name: crossplane
      version: 1.15.*
  install:
    createNamespace: true
    crds: Create
    disableWait: false
    disableWaitForJobs: false
    remediation:
      retries: -1
  interval: 60m
  releaseName: crossplane
  test:
    enable: false
  timeout: 5m
  upgrade:
    crds: CreateReplace
    disableWait: false
    disableWaitForJobs: false
    remediation:
      retries: -1
  values:
    installCRDs: true
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  labels:
    app.kubernetes.io/managed-by: timoni
    app.kubernetes.io/name: crossplane
    app.kubernetes.io/version: 2.4.0-2
  name: crossplane
  namespace: flux-system
spec:
  interval: 12h
  provider: generic
  url: https://charts.crossplane.io/stable
