apiVersion: meta.dev.upbound.io/v1alpha1
kind: Project
metadata:
  name: my-demo
spec:
  dependsOn:
  - provider: xpkg.upbound.io/upbound/provider-gcp-storage
    version: v1
  - provider: xpkg.upbound.io/upbound/provider-aws-s3
    version: v1
  - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
    version: v0.4.1
  - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
    version: v0.8.1
  - provider: xpkg.upbound.io/upbound/provider-gcp-artifact
    version: v1
  - provider: xpkg.upbound.io/upbound/provider-aws-ecr
    version: v1
  - provider: xpkg.upbound.io/upbound/provider-gcp-compute
    version: v1
  description: This is where you can describe your project.
  license: Apache-2.0
  maintainer: Upbound User <user@example.com>
  readme: |
    This is where you can add a readme for your project.
  repository: xpkg.upbound.io/yurikrupnik/my-demo
  source: github.com/yurikrupnik/mussia33
