#apiVersion: rbac.authorization.k8s.io/v1
#kind: Role
#metadata:
#  name: argo-role
#  namespace: default
#rules:
#  - apiGroups: ["argoproj.io"]
#    resources: ["workflowtaskresults"]
#    verbs: ["create", "get", "list", "watch"]
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: RoleBinding
#metadata:
#  name: argo-rolebinding
#  namespace: default
#subjects:
#  - kind: ServiceAccount
#    name: default
#    namespace: default
#roleRef:
#  kind: Role
#  name: argo-role
#  apiGroup: rbac.authorization.k8s.io
