name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: "dist/target"
          cache-all-crates: true
      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: bunx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"


      - run: bun install --no-cache
      - uses: nrwl/nx-set-shas@v4

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: bun nx-cloud record -- echo Hello World
      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      - run: bun nx affected --target=e2e --parallel --max-parallel=3
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: "dist/target"
          cache-all-crates: true
      - run: bun install --no-cache
      - uses: nrwl/nx-set-shas@v4
      - run: bun nx affected --target=lint --parallel --max-parallel=3
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: "dist/target"
          cache-all-crates: true
      - run: bun install --no-cache
      - uses: nrwl/nx-set-shas@v4
      - run: bun nx affected --target=test --parallel --max-parallel=3
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: "dist/target"
          cache-all-crates: true
      - run: bun install --no-cache
      - uses: nrwl/nx-set-shas@v4
      - run: bun nx affected --target=build --parallel --max-parallel=3
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: "dist/target"
          cache-all-crates: true
      - run: bun install --no-cache
      - uses: nrwl/nx-set-shas@v4
      - run: bun nx affected --target=docker --parallel --max-parallel=3
